<a href="https://colab.research.google.com/github/himani098/python-fundamentals/blob/main/day10_2026_06_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**creating array from list**

1d

2d

In [2]:
# list 1d
l = [1,2,3]
print(l)

import numpy as np
# array 1d
arr = np.array(l)
# arr -> variable name
# array() is a NumPy function used to create a NumPy array.
print(arr)

[1, 2, 3]
[1 2 3]


In [4]:
# 2d example

import numpy as np
# 2d list
l = [[1,2,3],[4,5,6]]
print(l)
print(l[0])
print(l[0][0])
# l([row][column])

# question list value 4 -> 100
l[1][0] = 100
print(l[1])
print("\n")

# 2d array
arr = np.array([[1,2,3],[4,5,6]])
# only 1 argument can be passed so putted all lists in one bracket
print(arr)
print(arr[0])
print(arr[0][0])

# question array value 4 -> 100
arr[1][0] = 100
print(arr[1])

[[1, 2, 3], [4, 5, 6]]
[1, 2, 3]
1
[100, 5, 6]


[[1 2 3]
 [4 5 6]]
[1 2 3]
1
[100   5   6]


**list vs numpy array**

1) Example of multi with
2) list and array
3) time comparsion
4) zeros (3,4)
5) ones (2,3)
6) full ((2,2),7)
7) random (2,3)
8) arange (0,10,2)

In [7]:
# list
l = [1,2,3]
lm = l*2
print(lm)

# array
import numpy as np
arr = np.array(l)
arrM = arr*2
print(arrM)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [9]:
# comparsion
# array running timing less than list
import numpy as np
import time
#Used to measure time.

# list
start = time.time()
#Stores the current time in seconds.
l = [i*500 for i in range(1000000)]
print("list output:",time.time() - start)
#Current Time - Starting Time
#This tells how long the code took to run

# array
start = time.time()
arr = np.arange(1000000)*500
print("array output:",time.time() - start)

list output: 0.08880305290222168
array output: 0.007634162902832031


use of zeros and ones - if we have any missing value in a data then we can replace it by a zero or one or we can remove/delete it or we can take out it's mean and save it

In [11]:
# zeros array 1d
#Creates an array filled with 0s.

import numpy as np
arr =  np.zeros(5)
print(arr)
print("\n")

# zeros array 2d
arr1 = np.zeros((3,4))
print(arr1)

[0. 0. 0. 0. 0.]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
# ones array 1d
#Creates an array filled with 1s.

import numpy as np
arr = np.ones(5)
print(arr)
print("\n")

# ones array 2d
arr1 = np.ones((3,4))
print(arr1)

[1. 1. 1. 1. 1.]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
#question
# create a 2D array with zeros and increment each element by 10

import numpy as np
arr = np.zeros((3,4))
print(arr)
print("\n")
print(arr+10)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]


In [17]:
#question
# create a 2D array with ones and multiply each element by 5

import numpy as np
arr = np.ones((3,4))
print(arr)
print("\n")
print(arr*5)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [21]:
# full for 1d
#Used to create an array filled with the same value.
#np.full(shape, value)

import numpy as np
arr = np.full((3),5)
# 3 elements in 1D with value 5
print(arr)
print("\n")

# full for 2d
import numpy as np
arr1 = np.full((2,3),5)
# 2 rows & 3 columns in 2D with value 5
print(arr1)

[5 5 5]


[[5 5 5]
 [5 5 5]]


In [22]:
#question
# create a 2D array with zeros and value of each element as 5
# create a 2D array with full and value of each element as 1

import numpy as np

arr = np.zeros((3,4)) + 5
print(arr)
print("\n")

arr1 = np.full((3,4),1)
print(arr1)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [24]:
#random for 1d
#Used to generate random decimal numbers between 0 and 1

import numpy as np
arr = np.random.random(5)
print(arr)
print("\n")

# random for 2d
arr1 = np.random.random((2,3))
print(arr1)

[0.38020545 0.56993757 0.23320469 0.12910887 0.80326054]


[[0.76348336 0.83299899 0.42654615]
 [0.06911377 0.29720244 0.37531892]]


In [25]:
#arange for 1d
#Creates an array of numbers in a range.

import numpy as np
arr = np.arange(5) # from 0 to 4
print(arr)
print("\n")

#arange for 1d || to convert into 2d -> reshape
arr1 = np.arange(0,10,2) # start,stop,step
print(arr1)

[0 1 2 3 4]


[0 2 4 6 8]



**Vector,matrix,tensor**

1) vector (1d)
2) matrix (2d)
3) tensor (3d)

In [27]:
import numpy as np

# vector 1d list
l = [1,2,3]
print(l)
print("\n")

# vector 1d array
arr = np.array(l)
print(arr)
print("\n")

# matrix 2d list
l = [[1,2,3],[4,5,6]]
print(l)
print("\n")

# matrix 2d array
arr = np.array(l)
print(arr)
print("\n")

# tensor 3d list
l = [[[1,2],[3,4]],[[5,6],[7,8]]]
print(l)
print("\n")

# tensor 3d array
arr = np.array(l)
print(arr)

[1, 2, 3]


[1 2 3]


[[1, 2, 3], [4, 5, 6]]


[[1 2 3]
 [4 5 6]]


[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]



**Array properties**

1) shape
2) dimension | direction
3) size
4) dtype

In [31]:
# array
import numpy as np
arr = np.arange(12) # 1d
print(arr)
# print("shape: ",arr.shape)
print("shape:",np.shape(arr)) # in form of single row or rows & columns
# arr.shape → property/attribute
# np.shape(arr) → NumPy function

print("dimension: ",np.ndim(arr))
print("size: ",np.size(arr)) # total elements
print("datatype: ",arr.dtype)
# int64 -> All elements are integers

[ 0  1  2  3  4  5  6  7  8  9 10 11]
shape: (12,)
dimension:  1
size:  12
datatype:  int64


In [32]:
# array
import numpy as np
arr = np.arange(12).reshape(3,4) # 3 X 4 => 12  # 2d
print(arr)
print("shape:",np.shape(arr))
print("dimension: ",np.ndim(arr))
print("size: ",np.size(arr))
print("datatype: ",arr.dtype)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape: (3, 4)
dimension:  2
size:  12
datatype:  int64
